### ISSUE TITLE
Allow sharing integrations 

### ISSUE THREAD

**Issue by JoBrad** [KOTechnologiesLtd/terraform-provider-cloudcraft#13]
When an integration is created, I should be able to share it with the team. This also seems to be missing from the public API, from what I can tell. 

Example terraform code I'd like to be able to configure: 

```
resource "cloudcraft_integration_aws" "main" {
  name = local.aws_account_name
  rolearn = module.cloudcraft.cloudcraft_role_arn
  sharedwith = [local.cloudcraft_team_id]
} 
```

**Comment by KOTechnologies** [comment]
@JoBrad Thanks for opening this issue. We will take a look.

**Comment by KOTechnologies** [comment]
@JoBrad Thanks for your patience with this issue.
You're right about the public api not supporting this feature at the moment and so we are unable to implement this at the moment. 
Upon checking their new go client, it isn't within their either.
https://github.com/DataDog/cloudcraft-go/blob/trunk/aws.go

We will close this issue for now.

**Comment by matzegebbe** [comment]
Hey! It looks like the API supports that:

I just created it via the web UI and noticed that the payload to https://app.cloudcraft.co/api/aws/account looks like this:

```json
{"name":"test-team","roleArn":"arn:aws:iam::${ACCOUNT_ID}:role/CloudCraftCrossAccountRole","externalId":"${EXTERNAL_ID}","readAccess":["team/${TEAM_UUID}"],"writeAccess":["team/${TEAM_UUID}"],"region":"us-east-1"}
```

You can find readAccess and writeAccess here: https://github.com/DataDog/cloudcraft-go/blob/trunk/aws.go#L47. And here https://docs.datadoghq.com/cloudcraft/api/#access-control-lists saying **Blueprints and AWS Accounts support the following access control properties**

The team uuid can be found in the API as well here: https://app.cloudcraft.co/api/team

**Comment by KOTechnologies** [comment]
Hello @JoBrad , 
There is a new CloudCraft provider with this feature implemented.
Thanks,
Vijay
